# What is Jupyter Notebook
*  The Jupyter Notebook is an open-source web application that allows you to create and share documents that contain live    code, equations, visualizations and narrative text.
* Uses include: data cleaning and transformation, numerical simulation, statistical modeling, data visualization, machine learning etc..
* The Notebook has support for over 40 programming languages, including Python, R, Julia, and Scala.
* The Jupyter Notebook App is a server-client application that allows editing and running notebook documents via a web browser.
* The Jupyter Notebook App can be executed on a local desktop requiring no internet access (as described in this document) or can be installed on a remote server and accessed through the internet.

In [14]:
# Python Programming Language :Types and Sequences
type('data science')
s=[1,2,3,4,5]
type(s)

list

In [15]:
s=(1.2,2.3,23.4)
type(s)

tuple

In [16]:
a=3.4
type(a)

float

In [17]:
list=[1,2,3,4,8,5,6]
for i in list:
    print(i,end=' ')

1 2 3 4 8 5 6 

In [18]:
j=0
while(j!=len(list)):
    print(list[j])
    j+=1

1
2
3
4
8
5
6


In [21]:
[1,2]+[3,4]+[4,5]

[1, 2, 3, 4, 4, 5]

In [22]:
[1,2,3]*5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [30]:
# Slicing Operation
s='welcome to DataScience'
s[0:]
s[::-1]
print(s[2:8])

lcome 


In [35]:
firstname='Polineni'
lastname='Anil'
print(firstname+""+lastname)

PolineniAnil


In [39]:
email={'anil':'anilpolineni09@gmail.com','polineni':'anil.p@apssdc.in'}
email['anil']
for key in email.keys():
    print(key)
for val in email.values():
     print(val)

anil
polineni
anilpolineni09@gmail.com
anil.p@apssdc.in


In [42]:
# Format Method
mail='iam {} my my mail id is{}'.format(email.keys(),email['anil'])
mail

"iam dict_keys(['anil', 'polineni']) my my mail id isanilpolineni09@gmail.com"

# Date And Time Modules

import datetime
#dir(datetime) 

In [72]:
import time  
t = time.localtime()  
print(time.asctime(t))


Wed Jul 10 14:00:41 2019


In [6]:
import time  
print(time.gmtime())


time.struct_time(tm_year=2019, tm_mon=7, tm_mday=10, tm_hour=6, tm_min=11, tm_sec=55, tm_wday=2, tm_yday=191, tm_isdst=0)


In [57]:
import time as tm
import datetime as dt
tm.ctime()
tm.time()
ds=dt.datetime.fromtimestamp(tm.time())
ds.month
ds.year
ds.day
ds.hour
ds.minute
ds.second

51

# Numpy  
* NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. 
* Using NumPy, mathematical and logical operations on arrays can be performed


In [60]:
import numpy as np
a=[1,2,3,4,5,3,6,7,8,8,9]   # Creating using numpy
data=np.array(a)
print(data)

[1 2 3 4 5 3 6 7 8 8 9]


In [67]:
import numpy as np
s=np.array([[1,2,3,4,5],[6,7,8,9,10]]) # 2D array using matricies 
print(s)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [68]:
data=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]) # 3D array using matrices
print(data)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [71]:
# shapes
# Tuple of array dimensions.
# The shape property is usually used to get the current shape of an array.

data=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(data)
data.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


(3, 5)

In [4]:
# arange
#data=np.arange(0,50,2)
data=np.arange(0,101)
print(data)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [1]:
# random
import numpy as np
s=np.random.randint(0,20,size=(2,4))
s

array([[19,  3, 12,  6],
       [ 6,  0, 14, 12]])

In [24]:
#Reshape: it returns the list of elements in the format of rows and columns.
import numpy as np
data=np.arange(0,100)
print(data)
data=data.reshape(10,10)
data


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [28]:
#Reshape: it returns the list of elements in the format of rows and columns.
import numpy as np
data=np.arange(0,50)
print(data)
data=data.reshape(5,10)
data


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [62]:
#Linspace: it returns a list at a specified range.
import numpy as np
data=np.linspace(0,8,10)
data


array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

In [65]:
# Resize:  it working like as reshape()

import numpy as np
data=np.linspace(0,8,9)
#data
data.resize(3,3)
data

# Built in Functions
  ##### ones --> it will take upto 3  posittional arguments(min 2)
  ##### zeros -->it will take upto 3  posittional arguments(min 2)

In [82]:
import numpy as np
data=np.ones((4,3)) # by default it will return Float value
data

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [83]:
import numpy as np
data=np.ones((4,3),int)  # it will return integer value
data

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [70]:
import numpy as np
data=np.zeros((4,3))
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [92]:
# V-Stack: Stack arrays in sequence vertically (row wise).
n=np.ones([4,4],int)
n
np.vstack([n,10*n])


array([[ 1,  1,  1,  1],
       [ 1,  1,  1,  1],
       [ 1,  1,  1,  1],
       [ 1,  1,  1,  1],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [100]:
# H-Stack: Stack arrays in sequence horizontally (column wise).
import numpy as np
n=np.ones([3,4],int)
n
np.hstack([n,2*n])

array([[1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2],
       [1, 1, 1, 1, 2, 2, 2, 2]])

# operators


In [104]:
import numpy as np
n=np.array([1,2,3,4,5])
n1=np.array([0,9,8,7,6])
n+n1

array([ 1, -7, -5, -3, -1])

In [107]:
import numpy as np
n=np.array([11,56,34,67,87])
n1=np.array([11,22,32,87,90])
n-n1

array([  0,  34,   2, -20,  -3])

In [110]:
import numpy as np
n=np.array([6,8,3,3])
n1=np.array([7,4,38,9])
n*n1
n**n1

array([    279936,       4096, -400556711,      19683], dtype=int32)

# BODMAS 
* Brackets of division
* Multiplication
* Addition
* Subtraction

In [112]:
# Dot: Return the dot product of two vectors.
import numpy as np
n=np.array([11,56,34,67,87])
n1=np.array([11,22,32,87,90])
n.dot(n1)

16100

In [117]:
import numpy as np
n=np.array([1,2,3,4,5])
n1=np.array([n,n**2])
n1

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [118]:
import numpy as np
n=np.array([1,2,3,4,5])
n1=np.array([n,pow(n,3)])
n1

array([[  1,   2,   3,   4,   5],
       [  1,   8,  27,  64, 125]])

# Transpose
* T ---> Attribute for Transpose
* transpose()

In [127]:
import numpy as np
n=np.array([[1,2,3,4,5],[0,9,8,7,6]])
n.T

array([[1, 0],
       [2, 9],
       [3, 8],
       [4, 7],
       [5, 6]])

In [128]:
import numpy as np
n=np.array([[1, 0],
           [2, 9],
           [3, 8],
           [4, 7],
           [5, 6]])
n.T

array([[1, 2, 3, 4, 5],
       [0, 9, 8, 7, 6]])

In [131]:
import numpy as np
n=np.array([[1,2,3,4],[4,5,6,7]])
n
n.transpose()

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

# Array datatype conversion:   
### Here we are discussing mainly two methods name as dtype() and astype().
*  by using dtype() we can find the list of  values belongs  to which type.
*  by using astype() we can perform the type conversions.


In [148]:
import numpy as np
n=np.array([1,3,5,7,9])
n
n.astype(int)
n.dtype

dtype('int32')

In [149]:
import numpy as np
n=np.array([1.5,3,5,7,9])
n
n.astype(int)
n.dtype

dtype('float64')

In [154]:
import numpy as np
n=np.array([1,2,3,4,5,6,7])
n
n.astype(int)
n.dtype

dtype('int32')

In [158]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
data
#data.min()

array([[ 3,  8, 11],
       [11,  3,  1],
       [ 6,  2,  3],
       [ 1, 10,  0]])

In [160]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.min()

[[10  9  7]
 [ 7  5  2]
 [ 1  4 13]
 [12  4 11]]


1

In [161]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.max()

[[ 0  7  2]
 [ 0  7  9]
 [ 2 12 14]
 [ 3 10  1]]


14

In [162]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.mean()

[[ 9  1  8]
 [ 0  3  7]
 [10 14  8]
 [14 13  8]]


7.916666666666667

In [163]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.std()

[[ 5  9  1]
 [14  8  4]
 [ 3  6  4]
 [12 13 10]]


4.050891534245545

In [165]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.argmin()

[[11 10  4]
 [13  0  1]
 [ 4  3  4]
 [13  4 11]]


4

In [166]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.argmax()

[[ 8  6  2]
 [ 7  1 14]
 [ 9  7 10]
 [11 13 11]]


5

In [167]:
import numpy as np
data=np.random.randint(0,15,size=(4,3))
print(data)
data.sum()

[[ 2  8  9]
 [10 10  1]
 [ 0 14 14]
 [ 9  2  5]]


84